# Generated by Django 5.1.1 on 2024-10-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conjugation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=100)),
                ('tense', models.CharField(choices=[('present', 'Present'), ('passecompose', 'Passé Composé'), ('futursimple', 'Futur Simple')], max_length=20)),
            ],
        ),
    ]
