# Generated by Django 5.1.1 on 2024-10-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conjugations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjugation',
            name='subject',
            field=models.CharField(default='Je', max_length=20),
        ),
    ]
